#server:
#  port: 8180
#spring:
#  cloud:
#    nacos:
#      config:
#        import-check:
#          enabled: false
#      discovery:
#        enabled: false
#
logging:
  level:
    org.cvlab.aiedu: debug

## mybatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: org.cvlab.aiedu
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**/*.xml